# Generated by Django 5.0.6 on 2024-07-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroHorasExtras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_funcionario', models.CharField(max_length=100)),
                ('dias_uteis', models.IntegerField()),
                ('dsr', models.FloatField()),
                ('horas_extras_60', models.FloatField()),
                ('horas_extras_80', models.FloatField()),
                ('horas_extras_noturnas_80', models.FloatField()),
                ('horas_extras_100', models.FloatField()),
            ],
        ),
    ]
